"""
One-off script (round 8): refreshes Section 6.5 after the SECOND round of
Whisper fixes (fixed-size 30s windowing to replace a broken VAD helper,
quality-filter thresholds actually applied in batched mode, and
without_timestamps=False to stop truncation on dense speech) and the
resulting full 357-creator pipeline re-run.

Updates:
  - Table 6.5 (Precision@10 per config): 0.52/0.06/0.16/0.38/0.08 -> new numbers
  - Table 6.6 (silhouette per k): new k=3..15 scores, best k moves 5 -> 10
  - Figures 6.2-6.6: re-embeds the regenerated PNGs (same paths, new bytes)
  - Fig. 6.4 / Fig. 6.5 captions: k = 5 -> k = 10
  - Paragraph 374 (Task 1 findings) with the new numbers
  - Paragraph 375 (historical ES comparison): notes partial feedback coverage
  - Paragraph 376 (Whisper-fix paragraph): rewritten to cover all 5 bugs found
    across both rounds, with the updated hallucination count and P@10 numbers
  - Paragraph 382 (Task 2 findings): k = 10, new cluster sizes, new cohesion %
  - Conclusion (7.1) and Future Work (7.2) numbers

A .bak copy of the pre-edit file is written before any changes.

Run:
    python update_thesis_v8.py
"""
import os
import shutil

import docx
from docx.oxml.ns import qn

DOCX_PATH = r"C:\Users\vladimir\Downloads\249024_MasterThesis_Draft.docx"
DOCX_PATH_COPY = r"C:\Users\vladimir\Downloads\249024_MasterThesis_Draft 2_main.docx"
BACKUP_PATH = DOCX_PATH.replace(".docx", "_backup_before_v8.docx")

FIG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "thesis_figures")


def find_para(doc, needle):
    return next(p for p in doc.paragraphs if needle in p.text)


def set_para_text(paragraph, new_text):
    if len(paragraph.runs) != 1:
        raise ValueError(f"expected exactly 1 run, found {len(paragraph.runs)}: {paragraph.text[:60]!r}")
    paragraph.runs[0].text = new_text


def replace_image(doc, paragraph, new_path):
    for run in paragraph.runs:
        for blip in run._element.findall(".//" + qn("a:blip")):
            rId = blip.get(qn("r:embed"))
            image_part = doc.part.related_parts[rId]
            with open(new_path, "rb") as f:
                image_part._blob = f.read()
            return True
    raise ValueError("no image found in paragraph")


def main():
    shutil.copy(DOCX_PATH, BACKUP_PATH)
    print(f"Backup written to {BACKUP_PATH}")

    doc = docx.Document(DOCX_PATH)

    # --- Table 6.5: Precision@10 per config ---
    t5 = doc.tables[5]
    new_p10 = {"visual_only (1.00 / 0.00)": "0.48", "text_only (0.00 / 1.00)": "0.04",
               "50 / 50": "0.04", "85 / 15 (deployed)": "0.28", "15 / 85": "0.04"}
    for row in t5.rows[1:]:
        label = row.cells[0].text.strip()
        if label in new_p10:
            row.cells[1].paragraphs[0].runs[0].text = new_p10[label]
    print("Updated Table 6.5")

    # --- Table 6.6: silhouette per k ---
    t6 = doc.tables[6]
    new_sil = {3: "0.0621", 4: "0.0779", 5: "0.0806", 6: "0.0814", 7: "0.0736",
               8: "0.0815", 9: "0.0882", 10: "0.0939", 11: "0.0651", 12: "0.0619",
               13: "0.0645", 14: "0.0683", 15: "0.0726"}
    for row in t6.rows[1:]:
        k = int(row.cells[0].text.strip())
        row.cells[1].paragraphs[0].runs[0].text = new_sil[k]
    print("Updated Table 6.6")

    # --- Figures 6.2 - 6.6 (same paths, freshly regenerated bytes) ---
    fig_map = [
        (373, "fig_precision_comparison.png"),
        (381, "fig_silhouette_scores.png"),
        (384, "fig_cluster_scatter.png"),
        (386, "fig_cluster_sizes.png"),
        (388, "fig_same_cluster_pct.png"),
    ]
    for caption_idx, fname in fig_map:
        img_para = doc.paragraphs[caption_idx - 1]
        replace_image(doc, img_para, os.path.join(FIG_DIR, fname))
    print("Replaced 5 figures")

    # --- Fig captions: k = 5 -> k = 10 ---
    for idx in (384, 386):
        p = doc.paragraphs[idx]
        set_para_text(p, p.text.replace("k = 5", "k = 10"))

    # --- Para 374: Task 1 findings with the new numbers ---
    set_para_text(doc.paragraphs[374], (
        "Contrary to hypothesis H1, the purely visual configuration (1.00/0.00) achieved the highest "
        "average Precision@10 (0.48) among the five tested configurations, clearly exceeding the "
        "deployed 85/15 configuration (0.28); the text-only and text-heavy configurations (0.00/1.00 "
        "and 0.15/0.85) performed substantially worse (0.04 each), and the balanced 50/50 blend also "
        "underperformed the visual-only configuration (0.04). Hypothesis H1 is therefore not confirmed "
        "by this experiment: combining modalities did not outperform the best single modality. "
        "Relevance for this measurement was judged by directly inspecting a representative frame from "
        "each retrieved creator's video together with its transcription, rather than defaulting "
        "unlabeled results to \u201cnot relevant\u201d as in earlier passes, giving a more reliable precision "
        "estimate."
    ))

    # --- Para 375: historical ES comparison, now with only partial feedback coverage ---
    set_para_text(doc.paragraphs[375], (
        "The existing 0.85/0.15 validation result (0.64) remains considerably higher than the freshly "
        "measured value for the same configuration (0.28); Fig. 6.2 reports this historical figure "
        "directly rather than a freshly computed one, since Elasticsearch click-feedback from the "
        "Flask demo this round covered only two of the five test queries (makeup and cooking, each "
        "showing precision@10 = 0.20), too sparse for a reliable five-query average. The remaining gap "
        "between the historical and freshly measured 85/15 figures is best explained by the two "
        "evaluations testing different retrieved-creator subsets, and by the historical figure being "
        "based on a small, self-selected sample of results the user had already seen and liked; it "
        "should not be read as evidence that search quality has degraded."
    ))

    # --- Para 376: rewritten Whisper-fix paragraph covering all 5 bugs found across both rounds ---
    set_para_text(doc.paragraphs[376], (
        "A natural concern is that this result merely reflects poor transcription quality rather than "
        "a genuine limitation of the text modality. Manual inspection of the Whisper outputs, prompted "
        "by observed anomalies such as spurious Welsh phrases and severe truncation on clearly audible "
        "speech, revealed five implementation bugs: (1) greedy decoding (beam size 1) with no "
        "repetition penalty caused the model to loop on short phrases or drift into an incorrect "
        "language on ambiguous or musical audio; (2) the language tokenizer was cached per worker "
        "process rather than re-detected per video, so a single misdetected video could contaminate "
        "every subsequent video processed by the same worker; (3) audio chunking relied on a "
        "voice-activity-detection helper that produced empty or malformed chunks, silently discarding "
        "most of a video's audio beyond the first segment; (4) segment-level quality filters "
        "(no-speech, log-probability, and compression-ratio thresholds) were computed but never "
        "actually applied in the batched inference path; and (5) disabling timestamps to speed up "
        "decoding caused severe truncation on videos with continuous, non-silent speech. All five were "
        "fixed \u2014 beam size 5 with a repetition penalty of 1.3 and a 3-gram repeat block, per-item "
        "multilingual re-detection, fixed-size 30-second non-overlapping windows in place of the VAD "
        "helper, the quality filters applied in batched mode, and timestamps re-enabled \u2014 and the "
        "full pipeline was re-run on all 357 creators and 948 videos. The effect was substantial: the "
        "number of creators with Welsh-hallucinated transcripts dropped from 190/357 to 1/357. "
        "Re-running the Task 1 evaluation on the resulting embeddings did not change the conclusion, "
        "however \u2014 the purely visual configuration remained the clear winner (0.48 vs. 0.28 for "
        "85/15). This indicates that the weak contribution of text embeddings is not primarily a "
        "transcription-quality artifact: even with clean, accurate transcriptions, short-form TikTok "
        "content frequently pairs background music, jokes, or unrelated commentary with visuals "
        "unrelated to the spoken audio, so the transcript adds limited topical signal regardless of "
        "transcription accuracy."
    ))

    # --- Para 382: Task 2 findings, k = 10 ---
    set_para_text(doc.paragraphs[382], (
        "The silhouette score is maximized at k = 10 (0.0939), yielding ten clusters of size 72, 45, "
        "49, 42, 14, 15, 39, 13, 30, and 5 creators (Fig. 6.4, Fig. 6.5); every candidate k between 3 "
        "and 15 produced clusters of at least 5 creators, so this maximum is not an artifact of a "
        "degenerate single-outlier split. Absolute silhouette values in the 0.06-0.09 range are "
        "modest, which is expected: CLIP visual embeddings were not trained to separate TikTok content "
        "niches specifically, so cluster boundaries are soft rather than sharply delineated. "
        "Nevertheless, the clustering captures statistically real structure: for each of the five test "
        "queries, between 30% and 70% of the top-10 search results fall into a single dominant cluster "
        "(Fig. 6.6), well above the roughly 10% expected by chance with ten clusters of these sizes. "
        "This confirms hypothesis H2: although H1 was not confirmed for the search-relevance metric, "
        "the underlying visual embedding space does organize creators into semantically meaningful "
        "groups that align with the tested query niches."
    ))

    # --- Conclusion (7.1) ---
    p_concl = find_para(doc, "Section 6.5 additionally tested hypothesis H1")
    set_para_text(p_concl, (
        "Section 6.5 additionally tested hypothesis H1 (Section 1.5) by comparing five visual/text "
        "embedding weightings; contrary to expectations, the purely visual configuration outperformed "
        "all other weightings, including the deployed 85/15 configuration (0.48 vs. 0.28 average "
        "Precision@10), so H1 was not confirmed within the scope of this evaluation. Fixing five "
        "underlying Whisper transcription bugs (decoding repetition loops, per-worker language "
        "caching, broken audio-chunk windowing, unapplied quality filters, and timestamp-related "
        "truncation) and re-running the full evaluation on freshly generated embeddings did not change "
        "this conclusion, indicating the result reflects a genuine content mismatch between spoken "
        "audio and visual topic rather than a transcription-quality artifact. A complementary "
        "clustering analysis confirmed hypothesis H2: despite modest silhouette scores, the resulting "
        "embedding space still groups creators in a way that aligns with query intent (30-70% of "
        "top-10 results sharing a common cluster per query, well above chance). Taken together, these "
        "findings suggest that TikTok content in this domain is primarily visually driven, and that "
        "Whisper-transcription-derived text embeddings should be treated as a secondary, noisier "
        "signal rather than an equal partner to the visual signal."
    ))

    # --- Future Work (7.2): silhouette range ---
    p421 = find_para(doc, "Stronger clustering validation")
    set_para_text(p421, p421.text.replace("(0.05-0.11)", "(0.06-0.09)"))

    doc.save(DOCX_PATH)
    print(f"Saved updated thesis to {DOCX_PATH}")
    shutil.copy(DOCX_PATH, DOCX_PATH_COPY)
    print(f"Synced copy to {DOCX_PATH_COPY}")


if __name__ == "__main__":
    main()
